Updated README for qTest Manager chart.
QAS-Labs/qtest-chart pull request #138
Opened 2021-11-12 19:13 UTC by liemng

Added configurations for qTest Manager Helm Chart README.

2021-11-15 07:29 UTC, duypm commented on README.md
> +| `client.jdbc.postgres.url` | PSQL database URL | `jdbc:postgresql://host.docker.internal/qtest` |
I think it would worth to have a separate section mentioning that the default configuration is expecting a PostgreSQL and Elasticsearch service to be available at where and with what configuration (credential...)

2021-11-15 07:29 UTC, duypm commented on README.md
> +| `persistence.s3.accessKey` | S3 access key | "" |
Having both PV and S3 might confuse people in the getting started so it's better to omit S3 here and have a separate section just to configure qTest with it.

2021-11-22 15:23 UTC, pjaladi21 commented on README.md
> +helm install qtest-parameters qtest/qtest-parameters
I think we need to pass the namespace -n qtest

2021-11-22 15:27 UTC, pjaladi21 requested changes
I think the parameters need to be separated like the values which need to be changed like data-name URL, password, email credentials, S3.  The service port and other values are default which can be changed or not.

2021-11-22 16:11 UTC, liemng commented
> I think the parameters need to be separated like the values which need to be changed like data-name URL, password, email credentials, S3. The service port and other values are default which can be changed or not.

We will have a JSON schema to specify what is required vs optional.

2021-11-22 18:23 UTC, merged