Qk8 s 903
QAS-Labs/qtest-chart pull request #141
Opened 2021-11-23 13:31 UTC by subbuATB1

Ingress changes for non-prod onPremise QK8s-903

2021-11-23 14:10 UTC, subbuATB1 commented
Lint does not fail in local however its getting failed in Git
C:\subbu\tricentis\code\helm\qtest-chart>helm lint Charts/qtest-chart
==> Linting Charts/qtest-chart

1 chart(s) linted, 0 chart(s) failed

2021-11-23 14:40 UTC, byangtri commented
Validating maintainers...
41<https://github.com/QAS-Labs/qtest-chart/runs/4300204266?check_suite_focus=true#step:6:41>>>> git ls-remote --get-url origin
42<https://github.com/QAS-Labs/qtest-chart/runs/4300204266?check_suite_focus=true#step:6:42>>>> helm lint Charts/qtest-chart
43<https://github.com/QAS-Labs/qtest-chart/runs/4300204266?check_suite_focus=true#step:6:43>==> Linting Charts/qtest-chart
44<https://github.com/QAS-Labs/qtest-chart/runs/4300204266?check_suite_focus=true#step:6:44>Error:  templates/resourcequota.yaml: object name must be between 0 and 253 characters: ""

What you could do is possibly take the resourcequota from qtest-mgr helm chart as qtest-mgr is passing and qtest-chart is not.

Brandon Yang | DevOps Engineer


[http://signature.tricentis.com/Email_Signature_Tricentis_Generic_Footer.png]<https://www.tricentis.com/?utm_source=signature&utm_medium=email&utm_campaign=Tricentis%20Generic>

[http://signature.tricentis.com/Twitter.png]<https://twitter.com/Tricentis?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>    [http://signature.tricentis.com/Linkedin.png] <https://www.linkedin.com/company/tricentis-technology-&-consulting-gmbh/>     [http://signature.tricentis.com/Blog.png] <https://www.tricentis.com/blog/>

Tricentis USA Corp.; 2570 W El Camino Real, Suite 540, Mountain View, CA 94040
This email (including any attachments) contains information that may be privileged and confidential. If you are not the intended recipient of this communication, please delete this e-mail and notify Tricentis immediately

________________________________
From: subbareddyg ***@***.***>
Sent: Tuesday, November 23, 2021 9:10 AM
To: QAS-Labs/qtest-chart ***@***.***>
Cc: Brandon Yang ***@***.***>; Review requested ***@***.***>
Subject: Re: [QAS-Labs/qtest-chart] Qk8 s 903 (PR #141)


Lint does not fail in local however its getting failed in Git
C:\subbu\tricentis\code\helm\qtest-chart>helm lint Charts/qtest-chart
==> Linting Charts/qtest-chart

1 chart(s) linted, 0 chart(s) failed

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/QAS-Labs/qtest-chart/pull/141#issuecomment-976590730>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASPKQQI2ZUUO542ZM44C74DUNOOGTANCNFSM5ITQSEVA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-11-23 15:04 UTC, liemng commented on Charts/qtest-chart/templates/deployment.yaml
> +          mountPath: /mnt/host/c/mnt/data/storage
Can we have this in values file?  Linux won't have a C drive.

2021-11-23 15:06 UTC, liemng commented on Charts/qtest-chart/templates/ingress.yaml
> +  name: example-ingress
We should use ingress value name.

2021-11-23 15:07 UTC, liemng commented on Charts/qtest-chart/templates/ingress.yaml
> +  namespace: qtest
We should use Release.Namespace.

2021-11-23 15:08 UTC, liemng commented on Charts/qtest-chart/templates/ingress.yaml
> +  rules:
Don't use hard-coded values in template.

2021-11-23 15:09 UTC, liemng commented on Charts/qtest-chart/templates/storageclass.yaml
>    name: qtest-onpremise-storage
This needs to be a value to allow user to specify the value.

2021-11-23 15:10 UTC, liemng commented on Charts/qtest-chart/templates/storageclass.yaml
> +    storage: 2Gi
This needs to be in value.

2021-11-23 15:12 UTC, liemng commented on Charts/qtest-chart/values-nonprod-op.yaml
> +### Ingress/IngressClass (> K8s 1.18-1.22+) #####
Please trim this file down to include only overrided values.

2021-11-23 15:13 UTC, liemng commented on Charts/qtest-chart/values.yaml
> +  enabled: false
Why is HPA disabled?

2021-11-23 15:15 UTC, liemng commented on Charts/qtest-mgr/templates/storageclass.yaml
> +{{ if and .Values.testconductor.environment.isOnPremise true }}
Please don't have hard-coded values in template files.

2021-11-24 11:46 UTC, subbuATB1 commented on Charts/qtest-chart/templates/deployment.yaml
> +          mountPath: /mnt/host/c/mnt/data/storage
Yes, I made the change to move volume mounts to values.yaml files.

2021-11-24 11:49 UTC, subbuATB1 commented on Charts/qtest-chart/templates/ingress.yaml
> +  name: example-ingress
This is in qtest-chart which will be deleted, I did use Ingress name from values file in qtest-mgr charts.

2021-11-24 11:49 UTC, subbuATB1 commented on Charts/qtest-chart/templates/ingress.yaml
> +  namespace: qtest
This is in qtest-chart which will be deleted, I did use Ingress name from values file in qtest-mgr charts.

2021-11-24 11:52 UTC, subbuATB1 commented on Charts/qtest-chart/templates/ingress.yaml
> +  rules:
This qtest-chart/Charts/qtest-charts will be decommissioned and we will be using qtest-charts/Charts/qtest-mgr will be used.

2021-11-24 13:23 UTC, subbuATB1 commented on Charts/qtest-chart/templates/storageclass.yaml
>    name: qtest-onpremise-storage
Storage class hardcode values moved to values.yaml file

2021-11-24 13:23 UTC, subbuATB1 commented on Charts/qtest-chart/templates/storageclass.yaml
> +    storage: 2Gi
Moved to values.yaml file

2021-11-24 13:24 UTC, subbuATB1 commented on Charts/qtest-chart/values-nonprod-op.yaml
> +### Ingress/IngressClass (> K8s 1.18-1.22+) #####
It does not work keep only overridden values , we have to keep all the values of a tree/object along with overridden values

2021-11-24 13:26 UTC, subbuATB1 commented on Charts/qtest-mgr/templates/storageclass.yaml
> +{{ if and .Values.testconductor.environment.isOnPremise true }}
storageclass hardcoded values moved to values.yaml file

2021-11-24 20:32 UTC, isgo-golgo13 requested changes
Revisit hardcoded 'C'drives in the paths

2021-11-24 20:32 UTC, isgo-golgo13 commented on Charts/qtest-chart/templates/deployment.yaml
> +          mountPath: /mnt/host/c/mnt/data/storage
You need to get rid of the 'C' drive here. This is will explode on Linux machines. This value here needs to go in values-nonprod-op.yaml

2021-11-24 20:32 UTC, isgo-golgo13 commented on Charts/qtest-chart/templates/deployment.yaml
> +          mountPath: /mnt/host/c/mnt/data/qtest
You need to get rid of the 'C' drive here. This is will explode on Linux machines. This value here needs to go in values-nonprod-op.yaml

2021-11-24 20:32 UTC, isgo-golgo13 commented on Charts/qtest-chart/templates/ingress.yaml
> +  namespace: qtest
Subby why are you doing the changes in qtest-chart ? I thought we were doing the changes in qtest-mgr?

2021-11-24 20:32 UTC, isgo-golgo13 commented on Charts/qtest-chart/templates/storageclass.yaml
> +    path: /mnt/host/c/mnt/data/qtest
No C drive on Linux.  Your using WSL or MinGW locally?

2021-11-24 22:23 UTC, liemng commented on Charts/qtest-mgr/templates/deployment.yaml
> +          mountPath: /mnt/host/c/mnt/data/storage
This needs to go into values.yaml, and should not have C drive in there.

2021-11-24 22:23 UTC, liemng commented on Charts/qtest-mgr/templates/deployment.yaml
> +          mountPath: /mnt/host/c/mnt/data/qtest
Same comment as above

2021-11-24 22:24 UTC, liemng commented on Charts/qtest-mgr/templates/deployment.yaml
> +          mountPath: /mnt/host/c/mnt/data/storage
No values

2021-11-24 22:24 UTC, liemng commented on Charts/qtest-mgr/templates/deployment.yaml
> +          mountPath: /mnt/host/c/mnt/data/qtest
No values

2021-11-24 22:25 UTC, liemng commented on Charts/qtest-mgr/templates/deployment.yaml
> +          mountPath: /mnt/host/c/mnt/data/storage
No values

2021-11-24 22:25 UTC, liemng commented on Charts/qtest-mgr/templates/deployment.yaml
> +          mountPath: /mnt/host/c/mnt/data/qtest
No values

2021-11-24 22:26 UTC, liemng commented on Charts/qtest-mgr/templates/storageclass.yaml
> +  namespace: {{ .Values.namespace.name }}
Don't need namespace.name.  Use built-in Helm objects:  https://helm.sh/docs/chart_template_guide/builtin_objects/ (Release.Namespace)

2021-11-24 22:28 UTC, liemng commented on Charts/qtest-mgr/templates/storageclass.yaml
> +                - kind-worker
Why do we have Kind stuff in the template?  Customer can run in AWS (and will).  Any Kind stuff should be moved into the values yaml file.

2021-11-24 22:29 UTC, liemng commented on Charts/qtest-mgr/templates/storageclass.yaml
> +      storage: {{ .Values.storage.pv.size }}
Please use the correct value names as shown in the README file:  https://github.com/QAS-Labs/qtest-chart/blob/main/README.md

2021-11-24 22:29 UTC, liemng commented on Charts/qtest-mgr/templates/storageclass.yaml
> +    - {{ .Values.storage.pv.accessmode }}
Please use the correct value names as shown in the README file: https://github.com/QAS-Labs/qtest-chart/blob/main/README.md

2021-11-24 22:31 UTC, liemng commented on Charts/qtest-mgr/templates/storageclass.yaml
> +  storageClassName: {{ .Values.storage.storageclass.name }}
Add a condition in here.  If there is no storageClass defined, should not define it.  This is why your StorageClass does not work in Kind and you have to mount dirs by hand.

2021-11-24 22:31 UTC, liemng commented on Charts/qtest-mgr/values-nonprod-op.yaml
> +### Ingress/IngressClass (> K8s 1.18-1.22+) #####
Please include only values that you override.  Do not copy and paste everything.

2021-11-24 22:33 UTC, liemng requested changes
Please see my comments.  Also, please fix the lint issues and look at the value names in https://github.com/QAS-Labs/qtest-chart/blob/main/README.md and match them accordingly.

2021-11-24 22:41 UTC, liemng commented on Charts/qtest-chart/values-nonprod-op.yaml
> +### Ingress/IngressClass (> K8s 1.18-1.22+) #####
That's not true.

2021-11-29 12:21 UTC, pjaladi21 commented on Charts/qtest-chart/templates/deployment.yaml
> +          mountPath: /mnt/host/c/mnt/data/storage
Moved to values.yaml

2021-11-29 12:27 UTC, pjaladi21 commented on Charts/qtest-chart/templates/storageclass.yaml
> +    path: /mnt/host/c/mnt/data/qtest
Resolved

2021-11-29 12:35 UTC, pjaladi21 commented on Charts/qtest-chart/templates/storageclass.yaml
>    name: qtest-onpremise-storage
Moved to values.yaml

2021-11-29 12:55 UTC, pjaladi21 commented on Charts/qtest-mgr/templates/deployment.yaml
> +          mountPath: /mnt/host/c/mnt/data/storage
moved

2021-11-29 12:56 UTC, pjaladi21 commented on Charts/qtest-mgr/templates/deployment.yaml
> +          mountPath: /mnt/host/c/mnt/data/qtest
Moved

2021-11-29 13:01 UTC, pjaladi21 commented on Charts/qtest-mgr/templates/storageclass.yaml
> +  namespace: {{ .Values.namespace.name }}
This is already there so reusing

2021-11-29 14:24 UTC, pjaladi21 commented on Charts/qtest-mgr/values-nonprod-op.yaml
> +### Ingress/IngressClass (> K8s 1.18-1.22+) #####
Can we leave this as is and get back to it later

2021-11-29 14:24 UTC, pjaladi21 commented on Charts/qtest-mgr/values-nonprod-op.yaml
> +### Ingress/IngressClass (> K8s 1.18-1.22+) #####
Can we leave this as is and get back to it later

2021-12-08 22:28 UTC, closed without merging